"""Added user-task relationship

Revision ID: bae2ff8e9e37
Revises: 
Create Date: 2025-06-20 23:41:59.540044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bae2ff8e9e37'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('context', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index('ix_tasks_email', table_name='tasks')
    op.create_index(op.f('ix_tasks_context'), 'tasks', ['context'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_foreign_key(None, 'tasks', 'user', ['user_id'], ['user_id'])
    op.drop_column('tasks', 'email')
    op.drop_column('tasks', 'password')
    op.add_column('user', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index('ix_user_id', table_name='user')
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.drop_column('user', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.drop_column('user', 'user_id')
    op.add_column('tasks', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_context'), table_name='tasks')
    op.create_index('ix_tasks_email', 'tasks', ['email'], unique=False)
    op.drop_column('tasks', 'user_id')
    op.drop_column('tasks', 'status')
    op.drop_column('tasks', 'context')
    # ### end Alembic commands ###
